name: github pages

on:
  push:
    branches:
      - main  # set a branch to deploy
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # fetch Hugo themes, use recursive
          fetch-depth: 0 # fetch all history for .GitInfo and .Lastmod

      # submodules: recursive is as below command,
      # - run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # hugo-version: 'latest'
          hugo-version: '0.88.1'
          extended: true # update to true

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16' # as development environment

      - name: Cache Nodejs Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Dependencies
        run: npm install

      # debugging
      # - run: npm list -all
      # - run: tree
      # - run: ls -l themes/docsy/assets/vendor
      # - run: ls -l themes/docsy/assets/vendor/bootstrap/scss
      # - run: hugo -v

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
